# Generated by Django 4.2.3 on 2023-08-02 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("label", models.CharField(max_length=5)),
                (
                    "data_integer",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(2147483647),
                            django.core.validators.MinValueValidator(-2147483647),
                        ],
                    ),
                ),
            ],
        ),
    ]
