# Generated by Django 4.2.3 on 2023-08-12 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arm_architecture", "0002_alter_register_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="data_integer",
            new_name="value",
        ),
    ]
