# Generated by Django 4.2.3 on 2023-08-15 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arm_architecture", "0003_rename_data_integer_register_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="value",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(2147483648),
                    django.core.validators.MinValueValidator(-2147483648),
                ],
            ),
        ),
    ]
